name: Publish to NuGet

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Pack
        run: |
          dotnet pack \
          dropbox-sdk-dotnet/Dropbox.Api \
          -p:Configuration=Release \
          -p:Version=$(echo "${{ github.event.release.tag_name }}" | cut -c 2-) \
          -p:AssemblyOriginatorKeyFile=dropbox_api_key.snk \
          -p:SignAssembly=true
      - name: Push
        run: |
          dotnet nuget push \
          dropbox-sdk-dotnet/Dropbox.Api/bin/Release/Dropbox.Api.$(echo "${{ github.event.release.tag_name }}" | cut -c 2-).nupkg \
          --source https://api.nuget.org/v3/index.json \
          --api-key ${{ secrets.NUGET_TOKEN }}
